version : "3.9"

services:
  db:
    image: postgres
    env_file:
      - Backend/.env
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbv1
      - POSTGRES_PASSWORD=dbv1password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  web:
    image : janmark101/v1:0.4
    command : python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    
    depends_on:
    - db

  pgAdmin:
    image: dpage/pgadmin4
    env_file:
      - Backend/.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@op.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
      
volumes:
  pgdata:
    