# Generated by Django 4.2.5 on 2023-10-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApi', '0002_conversation_boss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='boss',
            new_name='user_id_boss',
        ),
    ]
